"""
cleanup_and_fix.py
==================
Run this from inside the Frontend/ folder:

    cd Frontend
    python cleanup_and_fix.py

What it does:
  1. Deletes unnecessary files and folders
  2. Fixes data path issues
  3. Verifies all required files are present
  4. Prints a final checklist
"""

import os
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))  # Frontend/ folder

# ─────────────────────────────────────────────────────────────────────────────
# 1. DELETE UNNECESSARY FILES & FOLDERS
# ─────────────────────────────────────────────────────────────────────────────
REMOVE = [
    "2022",          # old duplicate data folder
    "data.db",       # unused database file
    "__pycache__",   # python cache
    "code/__pycache__",
]

print("=" * 60)
print("  Step 1: Removing unnecessary files")
print("=" * 60)

for item in REMOVE:
    full = os.path.join(ROOT, item)
    if os.path.isdir(full):
        shutil.rmtree(full)
        print(f"  🗑️  Deleted folder: {item}")
    elif os.path.isfile(full):
        os.remove(full)
        print(f"  🗑️  Deleted file:   {item}")
    else:
        print(f"  ✅  Already clean:  {item}")


# ─────────────────────────────────────────────────────────────────────────────
# 2. VERIFY REQUIRED FOLDER STRUCTURE
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Step 2: Checking required folders")
print("=" * 60)

REQUIRED_DIRS = ["data", "model", "models", "code"]
for d in REQUIRED_DIRS:
    full = os.path.join(ROOT, d)
    if os.path.isdir(full):
        print(f"  ✅  {d}/")
    else:
        os.makedirs(full)
        print(f"  📁  Created missing folder: {d}/")


# ─────────────────────────────────────────────────────────────────────────────
# 3. VERIFY REQUIRED DATA FILES
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Step 3: Checking data files")
print("=" * 60)

DATA_FILES = [
    ("data/dataset.csv",              "Symptom dataset (in your 2022/ folder — copy it to data/)"),
    ("data/clean_dataset.tsv",        "Generated by train.py — run it if missing"),
    ("data/symptom_Description.csv",  "In your 2022/ folder — copy it to data/"),
    ("data/symptom_precaution.csv",   "In your 2022/ folder — copy it to data/"),
    ("data/diabetes.csv",             "Kaggle: Pima Diabetes"),
    ("data/heart.csv",                "Kaggle: Heart Disease"),
    ("data/parkinsons.csv",           "Kaggle: Parkinson's"),
    ("data/liver.csv",                "Kaggle: Liver Disease"),
    ("data/hepatitis.csv",            "Kaggle: HCV Hepatitis"),
    ("data/lung_cancer.csv",          "Already in data/"),
    ("data/kidney.csv",               "Kaggle: Chronic Kidney Disease"),
    ("data/breast_cancer.csv",        "Kaggle: Wisconsin Breast Cancer"),
]

missing_data = []
for fpath, note in DATA_FILES:
    full = os.path.join(ROOT, fpath)
    if os.path.isfile(full):
        print(f"  ✅  {fpath}")
    else:
        print(f"  ❌  MISSING: {fpath}  ← {note}")
        missing_data.append(fpath)


# ─────────────────────────────────────────────────────────────────────────────
# 4. VERIFY MODEL FILES
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Step 4: Checking model files")
print("=" * 60)

MODEL_FILES = [
    ("model/xgboost_model.json",       "Run: python code/train.py"),
    ("models/diabetes_model.sav",      "Run: python retrain_all_models.py"),
    ("models/heart_disease_model.sav", "Run: python retrain_all_models.py"),
    ("models/parkinsons_model.sav",    "Run: python retrain_all_models.py"),
    ("models/liver_model.sav",         "Run: python retrain_all_models.py"),
    ("models/hepititisc_model.sav",    "Run: python retrain_all_models.py"),
    ("models/lung_cancer_model.sav",   "Run: python retrain_all_models.py"),
    ("models/chronic_model.sav",       "Run: python retrain_all_models.py"),
    ("models/breast_cancer.sav",       "Run: python retrain_all_models.py"),
]

missing_models = []
for fpath, note in MODEL_FILES:
    full = os.path.join(ROOT, fpath)
    if os.path.isfile(full):
        print(f"  ✅  {fpath}")
    else:
        print(f"  ❌  MISSING: {fpath}  ← {note}")
        missing_models.append(fpath)


# ─────────────────────────────────────────────────────────────────────────────
# 5. VERIFY CODE FILES
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  Step 5: Checking code files")
print("=" * 60)

CODE_FILES = [
    "app.py",
    "code/DiseaseModel.py",
    "code/helper.py",
    "code/train.py",
    "code/__init__.py",
    "retrain_all_models.py",
]

for fpath in CODE_FILES:
    full = os.path.join(ROOT, fpath)
    if os.path.isfile(full):
        print(f"  ✅  {fpath}")
    else:
        print(f"  ❌  MISSING: {fpath}")


# ─────────────────────────────────────────────────────────────────────────────
# 6. AUTO-COPY FILES FROM 2022/ IF STILL PRESENT
# ─────────────────────────────────────────────────────────────────────────────
old_folder = os.path.join(ROOT, "2022")
if os.path.isdir(old_folder):
    print("\n" + "=" * 60)
    print("  Step 6: Copying files from 2022/ → data/")
    print("=" * 60)
    copy_map = {
        "dataset.csv":             "data/dataset.csv",
        "disease_description.csv": "data/symptom_Description.csv",
        "disease_precaution.csv":  "data/symptom_precaution.csv",
        "symptom_severity.csv":    "data/symptom_severity.csv",
        "Testing.csv":             "data/Testing.csv",
        "Training.csv":            "data/Training.csv",
    }
    for src_name, dst_rel in copy_map.items():
        src = os.path.join(old_folder, src_name)
        dst = os.path.join(ROOT, dst_rel)
        if os.path.isfile(src) and not os.path.isfile(dst):
            shutil.copy2(src, dst)
            print(f"  📋  Copied {src_name} → {dst_rel}")
        elif os.path.isfile(dst):
            print(f"  ✅  Already exists: {dst_rel}")


# ─────────────────────────────────────────────────────────────────────────────
# 7. FINAL SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("  FINAL SUMMARY")
print("=" * 60)

if not missing_data and not missing_models:
    print("""
  ✅  Everything looks good!

  Run the app with:
      streamlit run app.py
""")
else:
    if missing_data:
        print("\n  ❌  Missing data files — download from Kaggle:")
        for f in missing_data:
            print(f"      {f}")

    if missing_models:
        print("\n  ❌  Missing model files — run:")
        print("      python retrain_all_models.py")

    print("""
  Once fixed, run the app with:
      streamlit run app.py
""")

print("  Ideal final structure:")
print("""
  Frontend/
  ├── app.py
  ├── retrain_all_models.py
  ├── requirements.txt
  ├── code/
  │   ├── __init__.py
  │   ├── DiseaseModel.py
  │   ├── helper.py
  │   └── train.py
  ├── data/
  │   ├── dataset.csv
  │   ├── clean_dataset.tsv
  │   ├── symptom_Description.csv
  │   ├── symptom_precaution.csv
  │   ├── diabetes.csv
  │   ├── heart.csv
  │   ├── parkinsons.csv
  │   ├── liver.csv
  │   ├── hepatitis.csv
  │   ├── lung_cancer.csv
  │   ├── kidney.csv
  │   └── breast_cancer.csv
  ├── model/
  │   └── xgboost_model.json
  └── models/
      ├── diabetes_model.sav
      ├── heart_disease_model.sav
      ├── parkinsons_model.sav
      ├── liver_model.sav
      ├── hepititisc_model.sav
      ├── lung_cancer_model.sav
      ├── chronic_model.sav
      └── breast_cancer.sav
""")
